# Generated by Django 5.2.1 on 2025-05-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='NoOfGuests',
            field=models.IntegerField(verbose_name='Number of Guests'),
        ),
    ]
