# Generated by Django 5.2.3 on 2025-06-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_booking_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_datetime',
            field=models.DateField(),
        ),
    ]
